### ISSUE TITLE
Exception when trying to open document from history DB

### ISSUE THREAD

**Issue by mgaerber** [axxepta/project-argon#27]
* use open url (CTRL-U)
* enter url of history entry (e.g. argon:/~history_trello/source/r_examples-of-boards_2016-02-12_12-26_v1r1.xml)

> [ class ro.sync.ui.application.d.l ]  -  java.lang.NullPointerException
java.lang.NullPointerException
	at org.basex.io.in.BufferInput.readByte(BufferInput.java:112)
	at org.basex.io.in.BufferInput.content(BufferInput.java:194)
	at org.basex.io.IOStream.read(IOStream.java:40)
	at de.axxepta.oxygen.api.RestConnection.request(RestConnection.java:175)
	at de.axxepta.oxygen.api.RestConnection.get(RestConnection.java:65)
	at de.axxepta.oxygen.customprotocol.ArgonProtocolHandler$ArgonConnection.getInputStream(ArgonProtocolHandler.java:45)
	at ro.sync.exml.editor.tb.d(Unknown Source)

**Comment by raducoravu** [comment]
Also run into this when double clicking a key definition in the DITA Maps Manager.

**Comment by mgaerber** [comment]
Has to do with special chars. In case of open URL the tilde symbol (~) will be converted to %7

**Comment by MarkusWb** [comment]
decode URL string before passing to get routine, set all files in hidden databases readonly
